pull_request_rules:
  # 1 — fast-track Codex PRs
  - name: flag & fast-track Codex
    conditions:
      - author=codex[bot]
    actions:
      label:
        add: [codex]
      review:
        type: APPROVE # auto-approve so the queue rule can count it
      delete_head_branch: {} # tidy up after merge

  # 2 — close PRs idle for 14 days (unless explicitly exempt)
  - name: close-dormant
    conditions:
      - updated-at < 14 days ago
      - label!=do-not-close
    actions:
      close: {}

queue_rules:
  - name: codex-fastlane
    conditions:
      - label~=codex
      - '#approved-reviews-by>=1'
      - check-success=Azure Pipelines / checks # required CI job
    batch_size: 10 # merge up to 10 PRs as one batch
    speculative_checks: 4 # keep four future batches pre-testing
