name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  checks:
    name: Lint • Tests • Coverage
    runs-on: ubuntu-24.04
    permissions: {contents: read}

    steps:
      # 1 Checkout
      - uses: actions/checkout@v4

      # 2 Node + pnpm (auto-cache)
      - uses: actions/setup-node@v4
        with: {node-version: 22.4.x}
      - uses: pnpm/action-setup@v2
        with: {version: 10.12, cache: true, run_install: false}

      # 3 Playwright browser cache (if smoke config later)
      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1

      # 4 Deps + browsers
      - run: pnpm install --frozen-lockfile
      - name: Install Playwright browsers
        run: pnpm dlx playwright install --with-deps

      # 5 Lint (non-blocking)
      - name: ESLint
        continue-on-error: true
        run: pnpm run lint

      # 6 Vitest unit + UI projects (single run)
      - name: Vitest
        run: pnpm vitest run --coverage

      # 7 Optionally run Playwright smoke if config file exists
      - name: Smoke tests
        if: ${{ hashFiles('tests/smoke.config.ts') != '' }}
        run: pnpm dlx playwright test --config=tests/smoke.config.ts

      # 8 Upload coverage
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f coverage/lcov.info -t $CODECOV_TOKEN

      # 9 SBOM
      - name: Generate SBOM
        run: pnpm dlx @cyclonedx/cyclonedx-node-pnpm --output sbom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
