name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  checks:
    name: Lint • Tests • Coverage
    runs-on: ubuntu-24.04 # GitHub-hosted runner
    permissions:
      contents: read

    steps:
      # ────────── 1. Checkout ──────────
      - uses: actions/checkout@v4

      # ────────── 2. Node.js runtime (no cache flag) ──────────
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      # ────────── 3. pnpm install + built-in cache ──────────
      #    • Installs pnpm 10.12
      #    • Restores / saves store cache automatically
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12
          run_install: false # we’ll run pnpm install later
          cache: true # built-in lock-file keyed cache

      # ────────── 4. Playwright browser cache ──────────
      - uses: actions/cache@v4
        id: pw-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1

      - name: Install Playwright browsers
        run: pnpm dlx playwright install --with-deps

      # ────────── 5. Project dependencies ──────────
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.verify-deps-before-run=true

      # ────────── 6. Lint ──────────
      - name: ESLint
        run: pnpm run lint

      # ────────── 7. Unit tests + coverage ──────────
      - name: Vitest
        run: pnpm run test -- --coverage

      # ────────── 8. Smoke tests (Playwright) ──────────
      - name: Playwright smoke tests
        run: pnpm dlx playwright test --config=tests/smoke.config.ts

      # ────────── 9. Codecov upload ──────────
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f coverage/lcov.info -t $CODECOV_TOKEN

      # ────────── 10. CycloneDX SBOM ──────────
      - name: Generate SBOM
        run: pnpm dlx @cyclonedx/cyclonedx-node-pnpm --output sbom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
