name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_call: {}

jobs:
  checks:
    name: Lint • Tests • Coverage
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Node + pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 22.4.x
          cache: pnpm

      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@10.12 --activate

      # Playwright browser cache
      - uses: actions/cache@v4
        id: pw-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-1

      - name: Install Playwright browsers
        run: pnpm dlx playwright install --with-deps

      # Project deps
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --config.verify-deps-before-run=true

      # Lint
      - name: ESLint
        run: pnpm run lint

      # Unit + coverage
      - name: Vitest
        run: pnpm run test -- --coverage

      # Smoke tests
      - name: Playwright smoke tests
        run: pnpm dlx playwright test --config=tests/smoke.config.ts

      # Codecov upload
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f coverage/lcov.info -t $CODECOV_TOKEN

      # SBOM artefact
      - name: Generate SBOM
        run: pnpm dlx @cyclonedx/cyclonedx-node-pnpm --output sbom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
